version: "2"
services:
    nginx:
        build: ./nginx/
        restart: always
        networks:
         - proxy
        ports:
         - "80:80"
         - "443:443"
        volumes:
         - /var/run/docker.sock:/tmp/docker.sock
networks:
    proxy:
        external: true
